apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  razorpay.webhook.secret: ii9DlFr3BeppkKnH8Nj6tS7L
  razorpay.key_id: rzp_test_sqbg3QV1uerVTH
  razorpay.key_secret: ii9DlFr3BeppkKnH8Nj6tS7L